import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Menu from "./components/menu/Menu";
import Footer from "./components/footer/Footer";
import { getCurrentUser, isUserAuthenticated } from "@/services/auth/auth.service";
import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "App Beneficios",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const isAuthenticated = await isUserAuthenticated();
  let userAuth;
  if (isAuthenticated) {
    userAuth = await getCurrentUser();
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <Menu isSession={isAuthenticated} userAuth={JSON.stringify(userAuth)}/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
